version: '2'
services:
  db:
    image: postgres
    volumes:
      - "./.data/db:/var/lib/postgresql"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: base_skeleton
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: secret

  web:
    depends_on:
      - db
    image: hnquang112/php7-laravel
    volumes:
      - "./src:/var/www/html"
    links:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: base_skeleton
      DB_USERNAME: docker
      DB_PASSWORD: secret