version: '2'
services:
  db:
    image: postgres:latest
    volumes:
      - "./.data/db:/var/lib/postgresql/data/pgdata"
    restart: always
    environment:
      # MYSQL_ROOT_PASSWORD: wordpress
      POSTGRES_DB: wordpress
      POSTGRES_USER: wordpress
      POSTGRES_PASSWORD: wordpress

  web:
    depends_on:
      - db
    image: hnquang112:php7-laravel
    # build: ./web
    links:
      - db
    ports:
      - "8000:80"
    restart: always
    # environment:
    #   WORDPRESS_DB_HOST: db:3306
    #   WORDPRESS_DB_PASSWORD: wordpress